version: 1
build:
  main: cmd/kyved
  proto:
    path: proto
    third_party_paths:
      - third_party/proto
      - proto_vendor
accounts:
  - name: dummy
    mnemonic: expect crisp umbrella hospital firm exhibit future size slot update blood
      deliver fat happy ghost visa recall usual path purity junior ring ordinary stove
  - name: alice
    coins:
      - 2000000000000000tkyve
    mnemonic: worry grief loyal smoke pencil arrow trap focus high pioneer tomato hedgehog
      essence purchase dove pond knee custom phone gentle sunset addict mother fabric
  - name: bob
    coins:
      - 1000000000000000tkyve
    mnemonic: crash sick toilet stumble join cash erode glory door weird diagram away
      lizard solid segment apple urge joy annual able tank define candy demise
  - name: charlie
    coins:
      - 1000000000000000tkyve
    mnemonic: shoot inject fragile width trend satisfy army enact volcano crowd message
      strike true divorce search rich office shoulder sport relax rhythm symbol gadget
      size
  - name: faucet
    coins:
      - 1000000000000000tkyve
    mnemonic: open home share route party lake room solution quantum pact model avocado
      humor dilemma review desert turtle total humor produce rate keen eagle fee
#  - name: team
#    coins:
#      - 165000000000000tkyve
#    address: kyve1e29j95xmsw3zmvtrk4st8e89z5n72v7nf70ma4
  - name: foundation
    coins:
      # for fees
      - 1000000tkyve
    mnemonic: evidence taxi material cabin annual phrase practice unhappy safe jealous
      section drink illness panther bread aim mouse dolphin deliver ready doll finger search cheap
#    address: kyve1fd4qu868n7arav8vteghcppxxa0p2vna5f5ep8
  - name: foundation_inflation
    coins:
      # for fees
      - 1000000tkyve
    mnemonic: hold urge sustain chef furnace foam oven fall harsh core anchor during crew secret
      craft rhythm choose gold soft aisle sort phrase enter orphan
#    address: kyve1tuxsc7ez79aydyee86qxm05zyx0l7d78c2zzsn

faucet:
  name: faucet
  coins:
    - 1000000000000tkyve
  host: 0.0.0.0:4500
client:
  openapi:
    path: docs/swagger/swagger.yml
genesis:
  app_state:
    bank:
      balances:
        - address: "kyve1e29j95xmsw3zmvtrk4st8e89z5n72v7nf70ma4"
          coins:
            - denom: "tkyve"
              amount: "165000000000000000"
    delegation:
      params:
        unbonding_delegation_time: 10
    global:
      params:
        burn_ratio: "0.5"
        min_gas_price: "1"
    gov:
      deposit_params:
        max_deposit_period: 300s
        min_deposit:
          - amount: "50_000_000_000"
            denom: tkyve
      voting_params:
        voting_period: 120s
    mint:
      params:
        mint_denom: "tkyve"
    team:
      account_count: "8"
      account_list:
        - id: "0"
          total_allocation: "1000000000000"
          unlocked_claimed: "0"
          clawback: "1686693600"
          commencement: "1663106400"
        - id: "1"
          total_allocation: "1000000000000"
          unlocked_claimed: "0"
          clawback: "1749852000"
          commencement: "1694642400"
        - id: "2"
          total_allocation: "1000000000000"
          unlocked_claimed: "0"
          clawback: "1694642400"
          commencement: "1615676400"
        - id: "3"
          total_allocation: "1000000000000"
          unlocked_claimed: "0"
          clawback: "1702508400"
          commencement: "1647212400"
        - id: "4"
          total_allocation: "1000000000000"
          unlocked_claimed: "0"
          clawback: "1741906800"
          commencement: "1663106400"
        - id: "5"
          total_allocation: "1000000000000"
          unlocked_claimed: "0"
          clawback: "1804978800"
          commencement: "1710370800"
        - id: "6"
          total_allocation: "1000000000000"
          unlocked_claimed: "0"
          clawback: "1741906800"
          commencement: "1615676400"
        - id: "7"
          total_allocation: "1000000000000"
          unlocked_claimed: "0"
          clawback: "1804978800"
          commencement: "1647212400"
    pool:
      pool_count: "2"
      pool_list:
        - config: "ar://tMTrJ8E3QgBNLz0-lyn6QrxasEIX46d14QFVmBWshSI"
          current_compression_id: "1"
          current_index: "0"
          current_key: ""
          current_storage_provider_id: "1"
          current_summary: '{"ADA":0.37775000000000003,"ATOM":11.012049999999999,"AVAX":17.7198,"BAT":0.28585000000000005,"BCH":124.7427,"BTC":27827.334000000003,"BUSD":0.99985,"DAI":1.00035,"DOGE":0.08305,"DOT":6.1640999999999995,"DYDX":2.5103999999999997,"EGLD":40.736450000000005,"ENJ":0.45815,"EOS":1.2001,"ETH":1852.6342,"FIL":5.5360499999999995,"FTM":0.45635,"KAVA":0.87035,"LDO":2.55,"LRC":0.3498,"LTC":89.62100000000001,"MANA":0.6005499999999999,"MATIC":1.0998999999999999,"MKR":701.0113,"NEAR":1.9702,"SAND":0.6326}'
          funders: []
          id: "0"
          logo: "ar://E3jXAOeJ3El7HQgOf_NtSOwVE7Sd0M4g4bYqjCBH9CU"
          max_bundle_size: "100"
          min_delegation: "100000000000"
          name: "Avalanche // C-Chain"
          operating_cost: "2500000000"
          disabled: false
          runtime: '@kyvejs/evm'
          start_key: "0"
          total_bundles: "1"
          total_funds: "0"
          upload_interval: "60"
          protocol:
            version: "1.0.0-beta.5"
            binaries: "{\"kyve-macos-x64\":\"https://github.com/KYVENetwork/kyvejs/releases/download/%40kyvejs%2Fevm%401.0.0-beta.5/kyve-macos-x64.zip\"}"
            last_upgrade: "0"
          upgrade_plan:
            version: ""
            binaries: ""
            scheduled_at: "0"
            duration: "0"
    stakers:
      params:
        commission_change_time: 10
    staking:
      params:
        bond_denom: tkyve
    bundles:
      finalized_bundle_list:
        - bundle_summary: '{"ADA":0.37775000000000003,"ATOM":11.012049999999999,"AVAX":17.7198,"BAT":0.28585000000000005,"BCH":124.7427,"BTC":27827.334000000003,"BUSD":0.99985,"DAI":1.00035,"DOGE":0.08305,"DOT":6.1640999999999995,"DYDX":2.5103999999999997,"EGLD":40.736450000000005,"ENJ":0.45815,"EOS":1.2001,"ETH":1852.6342,"FIL":5.5360499999999995,"FTM":0.45635,"KAVA":0.87035,"LDO":2.55,"LRC":0.3498,"LTC":89.62100000000001,"MANA":0.6005499999999999,"MATIC":1.0998999999999999,"MKR":701.0113,"NEAR":1.9702,"SAND":0.6326}'
          compression_id: 1
          data_hash: ""
          finalized_at:
            height: 1984
            timestamp: 441763200
          from_index: "42"
          from_key: "42"
          id: "0"
          pool_id: "0"
          storage_id: ""
          storage_provider_id: 1
          to_index: "69"
          to_key: "69"
          uploader: ""
  chain_id: kyve-local
validators:
  - name: alice
    bonded: 1000000000000tkyve
    config:
      consensus:
        timeout_commit: "2s"
        timeout_propose: "2s"
