on: push

jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      # Run `git checkout`
      - uses: actions/checkout@v3
      # Install `buf`
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}
      # Lint Protobuf files
      - uses: bufbuild/buf-lint-action@v1
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      # Run `git checkout`
      - uses: actions/checkout@v3
      # Install `go`
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false
      # Lint Go files
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=10m
